name : 002-workflow-events
on : 
  push:
  pull_request:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch:              # manually run a workflow from the GitHub UI, CLI, or API.


jobs :
    echo:
        runs-on: ubuntu-latest
        steps:
            - name : show the trigger
              run : echo "I have been triggered by ${{github.event_name}} event."