name: 003-workflow-runners
on:
  # push:
  workflow_dispatch:

jobs:
  ubuntu_job:
    runs-on: ubuntu-latest
    steps:
      - name: show OS
        run: |
          echo "This job runs on Ubuntu"
          echo "Finding runner using metadata so RUNNER is : $RUNNER_OS"
  windows_job:
    runs-on: windows-latest
    steps:
      - name: show OS
        shell: bash
        run: |
          echo "This job runs on Windows"
          echo "Finding runner using metadata so RUNNER is : $RUNNER_OS"
