name: 006-workflow-context
run-name: 06-Context | DEBUG - ${{inputs.debug}}
on: 
    push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false
jobs:
    wokflow-context-job:
        runs-on: ubuntu-latest
        steps :
            - name: context-job
              run: |
                echo "Event Name: ${{github.env}}"
                echo "Ref ${{github.ref}}"
                echo "Workflow ${{github.workflow}}"
                echo "Run id ${{github.run_id}}"
                echo "Run attempt ${{github.run_attempt}}"
            - name: retrieve vaiable
              run: |
                echo "Variable Name: ${{vars.my_secret}}"