name: 14-workflows-matrics
on:
    # push:
    workflow_dispatch:
jobs:
    job-maxtix:
        runs-on: ${{matrix.os}}
        strategy:
            matrix:
                node-version : [18.x,20.x,21.x]
                os:
                    - ubuntu-latest
                    # - windows-latest
                include:
                    - os : ubuntu-latest
                      node-version : 16.x
                    - os : ubuntu-latest
                      node-version : 21.x
                      tag : experimental

        steps:
            - name : node install
              uses : action/setup-node@V3
              with : ${{matrix.node-version}}
            - name : Fail job
              if   : matrix.tag == 'experimental'
              run  : exit1
            - name : Perform some tests
              run  : echo "Running test on ${{matrix.os}} and the version is ${{matrix.node-version}}"
