name: 15-workflows-environments
on :
    workflow_dispatch:
        inputs:
            select-env:
             type: environment
             default: QA
jobs:
    Env-details:
        runs-on : ubuntu-latest
        steps:
            - name : Selected env
              run: echo "The env is ${{inputs.select-env}}"

    Deploy-image-qa:
        runs-on : ubuntu-latest
        environment: QA
        needs: Env-details
        env:
            my-variable-status: ${{vars.TEST_VARIABLE||'deafult value'}}
        steps:
            - name : Selected env
              run: echo "The env is ${{inputs.select-env}}"
    Deploy-image-preprod:
        runs-on : ubuntu-latest
        environment: Preprod
        env:
            my-variable-status: ${{vars.TEST_VARIABLE||'deafult value'}}
        steps:
            - name : Selected env
              run: echo "The env is ${{inputs.select-env}}"
