name: 15.1-matrics-include-exclude
on:
    push:
    workflow_dispatch:
jobs:
    job-include-example:
      name : ${{matrix.color}}-${{matrix.shape}}-${{matrix.size}}
      runs-on: ubuntu-latest
      strategy:
          matrix:
              color : [red,green]
              shape : [circle,square]
              size : [large,small]
              include:
                - opacity : 50
                - color : red
                  opacity : 75
                  shape : triangle
                - color : green
                  opacity : 75
                  shape : square
                  size : xlarge
              exclude : 
                - color : green
                  shape : square
      steps:
          - name : Dummy step
            run  : echo "${{matrix.color}}-${{matrix.shape}}-${{matrix.size}}"
